# dockerfile

FROM rocker/tidyverse:4.4.3

# Copy renv.lock to use for package restoring
#COPY renv.lock /app/renv.lock

# Install dependencies and utilities
# RUN apt-get update && apt-get install -y \
# libcurl4-gnutls-dev
RUN apt-get update
RUN apt-get -y install libcurl4-openssl-dev libssl-dev make zlib1g-dev \
  libsodium-dev libicu-dev libpq-dev

# Install Node.js
# RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
# && apt-get install -y nodejs

# Workaround for renv cache -- may not be needed
RUN mkdir /.cache
RUN chmod 777 /.cache

RUN R -e "install.packages('renv', repos = c(CRAN = 'https://cloud.r-project.org'))"
# may not be needed

# Set the working directory to /app
WORKDIR /

# Copy the entire app directory into the container
COPY . .
# .Renviron needs to be copied

# install renv & restore packages -- can be combined with renv installation (see above)
RUN R -e 'renv::consent(provided = TRUE)'
RUN R -e "renv::restore()"

# expose port
EXPOSE 8008
ENTRYPOINT ["R", "-e", "run_plumber.R"]
